const { withXcodeProject } = require('@expo/config-plugins');

// `/ios` is generated by `expo prebuild` and gitignored, so anything set by
// hand in Xcode's Signing & Capabilities tab is lost on the next prebuild.
// This plugin writes the team back into the generated project every time, so
// archiving locally in Xcode works straight after a prebuild without clicking
// through the signing UI again.
//
// The team id is an account identifier, not a secret, but it is nobody's
// business in a public repo — it comes from the environment (see .env.example)
// rather than living in the source.
module.exports = function withSigning(config) {
  const developmentTeam = process.env.EXPO_APPLE_TEAM_ID;
  if (!developmentTeam) {
    // Loud on purpose: prebuild would otherwise succeed and the failure would
    // only surface much later, as an unsigned archive in Xcode.
    console.warn(
      '[withSigning] EXPO_APPLE_TEAM_ID is not set — the generated Xcode project ' +
      'will have no signing team. Set it (see .env.example) and prebuild again, ' +
      'or pick the team by hand in Xcode.'
    );
    return config;
  }

  return withXcodeProject(config, (config) => {
    const project = config.modResults;

    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigs)) {
      const settings = buildConfigs[key].buildSettings;
      // Only the app target carries PRODUCT_NAME; skip the project-level and
      // Pods configurations so we don't sign every dependency separately.
      if (!settings || settings.PRODUCT_NAME == null) continue;
      settings.DEVELOPMENT_TEAM = developmentTeam;
      settings.CODE_SIGN_STYLE = 'Automatic';
    }

    // Mirror it into the target attributes so Xcode's UI shows the team and
    // "Automatically manage signing" as already selected.
    const attributes = project.getFirstProject().firstProject.attributes;
    const targetAttributes = attributes.TargetAttributes ?? (attributes.TargetAttributes = {});
    for (const targetKey of Object.keys(targetAttributes)) {
      targetAttributes[targetKey].DevelopmentTeam = developmentTeam;
      targetAttributes[targetKey].ProvisioningStyle = 'Automatic';
    }

    return config;
  });
};
