const { withXcodeProject } = require('@expo/config-plugins');

// `/ios` is generated by `expo prebuild` and gitignored, so anything set by
// hand in Xcode's Signing & Capabilities tab is lost on the next prebuild.
// This plugin writes the team back into the generated project every time, so
// archiving locally in Xcode works straight after a prebuild without clicking
// through the signing UI again.
const DEVELOPMENT_TEAM = '356QWVB6D4';

module.exports = function withSigning(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;

    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigs)) {
      const settings = buildConfigs[key].buildSettings;
      // Only the app target carries PRODUCT_NAME; skip the project-level and
      // Pods configurations so we don't sign every dependency separately.
      if (!settings || settings.PRODUCT_NAME == null) continue;
      settings.DEVELOPMENT_TEAM = DEVELOPMENT_TEAM;
      settings.CODE_SIGN_STYLE = 'Automatic';
    }

    // Mirror it into the target attributes so Xcode's UI shows the team and
    // "Automatically manage signing" as already selected.
    const attributes = project.getFirstProject().firstProject.attributes;
    const targetAttributes = attributes.TargetAttributes ?? (attributes.TargetAttributes = {});
    for (const targetKey of Object.keys(targetAttributes)) {
      targetAttributes[targetKey].DevelopmentTeam = DEVELOPMENT_TEAM;
      targetAttributes[targetKey].ProvisioningStyle = 'Automatic';
    }

    return config;
  });
};
